Repository 25huizengek1/ViTune, pull requests merged in 2024-04, with the labels that each got.

#209 Adding Indonesian language to ViTune
  app/src/main/res/values-in/strings.xml
Labels: size/L

#222 feat(ui): Add precache button for non-Offline builtin playlists
  app/src/main/kotlin/app/vitune/android/ui/screens/builtinplaylist/BuiltInPlaylistSongs.kt
Labels: size/XS

#226 Update strings.xml
  app/src/main/res/values-de/strings.xml
Labels: size/S

#228 feat(ui): Rewrite color palette logic
  app/src/main/kotlin/app/vitune/android/MainApplication.kt
  app/src/main/kotlin/app/vitune/android/preferences/AppearancePreferences.kt
  app/src/main/kotlin/app/vitune/android/preferences/OldPreferences.kt
  app/src/main/kotlin/app/vitune/android/ui/screens/player/Lyrics.kt
  app/src/main/kotlin/app/vitune/android/ui/screens/player/PlaybackError.kt
  app/src/main/kotlin/app/vitune/android/ui/screens/player/Player.kt
  app/src/main/kotlin/app/vitune/android/ui/screens/settings/AppearanceSettings.kt
  app/src/main/kotlin/app/vitune/android/utils/MonetCompat.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values/strings.xml
  compose/preferences/src/main/kotlin/app/vitune/compose/preferences/PreferencesHolders.kt
  core/ui/src/main/kotlin/app/vitune/core/ui/Appearance.kt
  core/ui/src/main/kotlin/app/vitune/core/ui/ColorPalette.kt
  core/ui/src/main/kotlin/app/vitune/core/ui/Enums.kt
  core/ui/src/main/kotlin/app/vitune/core/ui/enums/ColorPaletteMode.kt
  core/ui/src/main/kotlin/app/vitune/core/ui/enums/ColorPaletteName.kt
  core/ui/src/main/kotlin/app/vitune/core/ui/utils/Saver.kt
Labels: enhancement, size/XL
