Repository 25huizengek1/ViTune, pull requests merged in 2024-10, with the labels that each got.

#452 Added support for Serbian language (latin letters)
  app/src/main/res/values-b+sr+Latn/strings.xml
Labels: size/L

#456 Russian language support!
  app/src/main/res/values-ru/strings.xml
Labels: size/L

#470 Minor translations fixes
  app/src/main/res/values-et/strings.xml
Labels: size/XS

#474 Made Latin to Cyrillic translation of Serbian translation.
  app/src/main/res/values-b+sr+Cyrl/strings.xml
Labels: size/L

#486 Update Chinese translations for string.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/M

#494 Minor translation fixes in Russian translation
  app/src/main/res/values-ru/strings.xml
Labels: size/M

#495 Sponsorblock description translation
  app/src/main/res/values-et/strings.xml
Labels: size/XS
